apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ws
  labels:
    app: user-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ws
  template:
    metadata:
      labels:
        app: user-ws
    spec:
      containers:
        - name: user-ws
          image: gcr.io/nlacombe-net-prod/user-ws:4.1.1-20201213192128
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 200Mi
            limits:
              cpu: 600m
              memory: 284Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-ws
spec:
  selector:
    app: user-ws
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: user-ws
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: user-api.nlacombe.net
      http:
        paths:
          - backend:
              serviceName: user-ws
              servicePort: 80
